FROM python:3.10

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

ARG APPLICATION_ENVIRONMENT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION

ENV APPLICATION_ENVIRONMENT=${APPLICATION_ENVIRONMENT}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 5000
EXPOSE 8000

CMD ["python", "__main__.py"]
